# Site settings
title: 春田花花疯人院
description: '院长团子的主页'
url: 'https://page.ikun.su'
baseurl: ''
profilepic: '/images/IMG_3541.gif'
bkimage: 'images/wallhaven-zy7wvj.png'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: '团子'
#  email: sep@aya.yale.edu
# mastodon: tzuehlke@mstdn.social
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
# github_username:  sepbigo
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
